### ISSUE TITLE
Package the extension so it can be installed via pip

### ISSUE THREAD

**Issue by jon-hagg** [Breakthrough-Energy/fs-azureblob#3]
# :rocket:

- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
Enable consumption of the extension by standard means

### Describe your proposed implementation
Steps to [create an extension](https://docs.pyfilesystem.org/en/v2.4.13/extension.html) from the docs. The main points are:
- [x] Add the `entry_points` to `setup.py`
- [x] Implement `Opener` subclass to handle custom url protocol
- [x] Add pypi token to github secrets
- [x] Add release.yml workflow to publish when new tags are created
- [ ] Create git tag to trigger workflow

### Describe alternatives you've considered, if relevant
n/a

### Additional context
Technically, we could use the extension without doing this, but it make the package consistent with other extensions and possibly worth listing as an "official" 3rd party extension

**Comment by robcowie** [comment]
Hi. Do you still have plans to package and deploy to PyPi?

**Comment by jon-hagg** [comment]
> Hi. Do you still have plans to package and deploy to PyPi?

Hi @robcowie - yes, certainly. I just got back from vacation so should have an initial release published soon.

**Comment by robcowie** [comment]
Outstanding! I see [0.1.0 on pypi](https://pypi.org/project/fs-azureblob/) already. Thanks for your efforts.

**Comment by jon-hagg** [comment]
Thanks for the interest! Just want to mention, I recommend reading the [note](https://github.com/Breakthrough-Energy/fs-azureblob#note) about directory structure if you plan on using it.
